pipeline {
      agent any
	
    tools {
        jdk '17'
        maven '3.9.4'
    }
    triggers {
      pollSCM ''
    }
     environment
    { 

        PROJECT = 'studentmanagement-springboot-app'
        IMAGE = 'studentmanagement-springboot-app:latest'
        DOCKERREPO= 'bmaddi' 

    }
    stages {

            stage('Maven Build'){
                steps{
                    echo "JAVA_HOME: ${env.JAVA_HOME}"
                    sh 'java -version'
                    sh 'mvn clean package -Dmaven.test.skip=true'
                }
            }
        stage('Build preparations')
        {
            steps
            {
                script
                {
		           // calculate GIT lastest commit short-hash
                    gitCommitHash = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()
                    shortCommitHash = gitCommitHash.take(7)
                    // calculate a sample version tag
                    VERSION = shortCommitHash
                    currentBuild.displayName = "${PROJECT}-${VERSION}"
                    IMAGE = "$DOCKERREPO/$PROJECT:${BUILD_NUMBER}.${VERSION}"
                }
            }
        }
            stage('Docker build')
        {
            steps
            {
                script
                {
                    // Build the docker image using a Dockerfile
                    docker.build("$IMAGE","-f Dockerfile .")
                }
            }
        }

   stage('Docker push')
        {
            steps
            {
                script
                {
                     withDockerRegistry([ credentialsId: "docker-hub-creds", url: "" ]) {
                     docker.image(IMAGE).push()
                    }
                }

                }
            }
   stage('Update Image Id in File') {
        environment {
            GIT_REPO_NAME = "student-managemnt-system-helmcharts"
            GIT_USER_NAME = "bhuvanchandmaddi"
        }
        steps {
            withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                sh '''
		    git clone https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}
                    cd student-managemnt-system-helmcharts
                    git config user.email "bhuvanchand@gmail.com"
                    git config user.name "BhuvanChand"
                    IMAGE_TAG=${BUILD_NUMBER}.${VERSION}"
                    sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" springboot-app/files/extfile.yaml
                    git add springboot-app/files/extfile.yaml
                    git commit -m "Update deployment image to version ${IMAGE_TAG}"
                    git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                '''
            }
        }
        
    }
    }
                    
    post {
      success {
       echo 'job is success'
      }
      aborted {
        echo 'aborted'
      }
      failure {
        echo 'failed job'
      }
      // cleanup {
      //   cleanWs()
      // }
  }
}
