pipeline {
      agent any
	
   

     environment
    { 

        PROJECT = 'studentmanagement-springboot-app'
        IMAGE = 'studentmanagement-springboot-app:latest'
        DOCKERREPO= 'bmaddi' 

    }
    stages {

            stage('Maven Build'){
                steps{
                    echo "JAVA_HOME: ${env.JAVA_HOME}"
                    sh 'java -version'
                    sh 'mvn clean package -Dmaven.test.skip=true'
                }
            }
        stage('Build preparations')
        {
            steps
            {
                script
                {
		           // calculate GIT lastest commit short-hash
                    gitCommitHash = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()
                    shortCommitHash = gitCommitHash.take(7)
                    // calculate a sample version tag
                    VERSION = shortCommitHash
                    currentBuild.displayName = "${PROJECT}-${VERSION}"
                    IMAGE = "$DOCKERREPO/$PROJECT:${BUILD_NUMBER}.${VERSION}"
		    IMAGE_TAG = "${BUILD_NUMBER}.${VERSION}"
		    env.IMAGE_TAG = IMAGE_TAG
                }
            }
        }
            stage('Docker build')
        {
            steps
            {
                script
                {
                    // Build the docker image using a Dockerfile
                    docker.build("$IMAGE","-f Dockerfile .")
                }
            }
        }

   stage('Docker push')
        {
            steps
            {
                script
                {
                     withDockerRegistry([ credentialsId: "docker-hub-creds", url: "" ]) {
                     docker.image(IMAGE).push()
                    }
                }

                }
            }

    }
                    
    post {
      success {
       echo 'job is success'
      }
      aborted {
        echo 'aborted'
      }
      failure {
        echo 'failed job'
      }
      cleanup {
        cleanWs()
      }
  }
}
