pipeline {
  agent any
    environment{
        registry = "bmaddi/studentmanagement-springboot-app"
        BRANCH = "main"
        APP_CONFIG_REPO_URL = "https://github.com/bhuvanchandmaddi/student-managemnt-system-helmcharts.git"
        image_tag = "18.daa4759"

    }

    stages {

		stage('Checkout Application Helmcharts'){
            steps{
				script{
					checkout([
						$class: 'GitSCM',
						branches: [[name: env.BRANCH ]],
							doGenerateSubmoduleConfigurations: false,
							submoduleCfg: [],
							userRemoteConfigs: [[url: env.APP_CONFIG_REPO_URL ]]])
				}
			}					
		}
        stage('Docker Pull')
        {
            steps
            {
                script
                {
		    IMAGE = "$registry:$image_tag"
                    withDockerRegistry(credentialsId: 'docker-hub-creds', url: '')                    
                    {
                        docker.image(IMAGE).pull()
                    }
                }
            }
        }

       
        stage('Install service') { 
            steps {
                        script{
			  def minikube_password = 'minikube'
			 // def KUBECONFIG = '/tmp/config'
	                  sh '''
                          echo "${minikube_password}" | sudo -u minikube -S helm upgrade --insecure-skip-tls-verify --install springbootapp  springboot-app/ -f springboot-app/files/extfile.yaml
                          '''
		}      
            }
        }
    }
    post { 
        always { 
			//sh "docker rmi $IMAGE | true"
            //cleanWs()
		echo "This will be executed always"
        }
    }    
}
