pipeline {
  agent any
    environment{
        registry = "bmaddi/studentmanagement-springboot-app"
        BRANCH = "main"
        APP_CONFIG_REPO_URL = "https://github.com/bhuvanchandmaddi/student-managemnt-system-helmcharts.git"
        image_tag = "33.e43f5eb"

    }

    stages {

		stage('Checkout Application Helmcharts'){
            steps{
				script{
					checkout([
						$class: 'GitSCM',
						branches: [[name: env.BRANCH ]],
							doGenerateSubmoduleConfigurations: false,
							submoduleCfg: [],
							userRemoteConfigs: [[url: env.APP_CONFIG_REPO_URL ]]])
				}
			}					
		}
        stage('Docker Pull')
        {
            steps
            {
                script
                {
		    IMAGE = "$registry:$image_tag"
                    withDockerRegistry(credentialsId: 'docker-hub-creds', url: '')                    
                    {
                        docker.image(IMAGE).pull()
                    }
                }
            }
        }

       
        stage('Install service') { 
            steps {
	        withCredentials([string(credentialsId: 'MINIKUBE_PASSWORD', variable: 'MINIKUBE_PASSWORD')]) {
                        script{
	                  sh '''
                          echo "${MINIKUBE_PASSWORD}" | sudo -u minikube -S helm upgrade --insecure-skip-tls-verify --install springbootapp  springboot-app/ -f springboot-app/files/extfile.yaml
                          '''
		     }
		}
            }
        }
    }
    post { 
        always { 
	    sh "docker rmi $IMAGE | true"
            cleanWs()
	    echo "This will be executed always"
        }
    }    
}
