pipeline {
  agent any
    environment{
        registry = "bmaddi/studentmanagement-springboot-app"
        BRANCH = "main"
        APP_CONFIG_REPO_URL = "https://github.com/bhuvanchandmaddi/student-managemnt-system-helmcharts.git"
        image_tag= "18.daa4759"

    }

    stages {

		stage('Checkout Application Helmcharts'){
            steps{
				script{
					checkout([
						$class: 'GitSCM',
						branches: [[name: env.BRANCH ]],
							doGenerateSubmoduleConfigurations: false,
							submoduleCfg: [],
							userRemoteConfigs: [[url: env.APP_CONFIG_REPO_URL ]]])
				}
			}					
		}
        stage('Docker Pull')
        {
            steps
            {
                script
                {
		    IMAGE = "$registry:$image_tag"
                    withDockerRegistry(credentialsId: 'docker-hub-creds', url: '')                    
                    {
                        docker.image(IMAGE).pull()
                    }
                }
            }
        }

       
        stage('Install service') { 
            steps {
                        script{
			  //def KUBECONFIG = '/tmp/config'
		          sh '''
                    export KUBECONFIG=/home/minikube/.kube/config
                    helm upgrade --insecure-skip-tls-verify --install springbootapp  student-managemnt-system-helmcharts/sprintboot-app -f student-managemnt-system-helmcharts/sprintboot-app/files/extfile.yaml
                    '''
		}      
            }
        }
    }
    post { 
        always { 
			sh "docker rmi $IMAGE | true"
            //cleanWs()
        }
    }    
}
