project: default
source:
  repoURL: 'https://github.com/bhuvanchandmaddi/student-managemnt-system-helmcharts.git'
  path: springboot-app
  targetRevision: HEAD
  helm:
    valueFiles:
      - files/extfile.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: springboot
syncPolicy:
  syncOptions:
    - CreateNamespace=true
